@startuml

(*) --> "RoI Segmentation"
partition Preprocessing {
--> "Color-distortion filtering"
--> "Band pass filter"
}
partition PulseDetection {
--> "POS or CHROM or Green"
}
partition Postprocessing {
--> "Moving Average Filter"
}
--> "PeakDetection"
--> (*)
@enduml
@enduml