@startuml

(*) --> "RoI Segmentation"
partition Preprocessing {
--> "Band pass filter"
--> "Color-distortion filtering"

}
partition PulseDetection {
--> "POS or CHROM or Green"
}
' partition Postprocessing {
' --> "Moving Average Filter"
' }
--> "PeakDetection"
--> (*)
@enduml