@startuml

(*) --> "PPG Signal"
partition Peak_Detection {
--> "Interpolate & UpSampling to 250Hz"
--> "Derivative Filter"
--> "Slope Sum Function"
--> "ppg peak detection"
--> "outlier removal and interpolation"
}

--> (*)
@enduml