@startuml

(*) --> "Record Video"
partition RoI_Segmentation {
--> "Detection/Tracking using Openface"
--> "RoI Segmentation"
--> "Skin area detection"
--> "Average RGB components in RoI"
}
--> "raw RGB signals"

partition Preprocessing {
 --> "未実装 Band pass filter  0.7-2.5Hz"
}

partition rPPG_Detection {
--> "loop from first to last frame in video sequence"
--> "spatical averaging"
--> "projection to skin"
--> "Compute rPPG signal(alpha-tuning)"
--> "overlap adding"
--> "slide 1 frame ...loop"
}
--> "rPPG signals"
' //https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5175543/
' // https://www.renesas.com/jp/ja/doc/products/mpumcu/apn/rl78/003/r11an0389jj0100-bsspf-apl.pdf
partition Peak_Detection {
--> "Interpolate & UpSampling"
--> "Low Pass Filter"
--> "High Pass Filter"
--> "Derivative Filter"
--> "Slope Sum Function"
--> "Moving Average Filter"
--> "Ca"
--> "time domain smoothing"
--> "frequency domain filter"
--> "ppg peak detection"
--> "outlier removal and interpolation"
}
--> "PPI signals"

--> (*)
@enduml