@startuml

(*) --> "Record Video"
partition RoI_Segmentation {
--> "Detection/Tracking using Openface"
--> "RoI Segmentation"
--> "Skin area detection"
--> "Average RGB components in RoI"
}
--> "raw RGB signals"

partition Preprocessing {
 --> "Band pass filter  0.7-2.5Hz"
}

partition rPPG_Detection {
--> "loop from first to last frame in video sequence"
--> "spatical averaging"
--> "projection to skin"
--> "Compute rPPG signal(alpha-tuning)"
--> "overlap adding"
--> "slide 1 frame ...loop"
}
--> "rPPG signals"

partition Peak_Detection {
--> "frequency filter"
--> "time domain smothing"
--> "ppg peak detection"
--> "outlier removal and interpolation"
}
--> "PPI signals"

--> (*)
@enduml